CREATE TABLE [dbo].[Grants]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [ClientId] NVARCHAR(30) NOT NULL, 
	[CreationTime] DATETIME NOT NULL DEFAULT GetDate(), 
    [Data] NVARCHAR(MAX) NOT NULL,  
	[Expiration] DATETIME NOT NULL DEFAULT GetDate(),
	[Key] NVARCHAR(MAX) NOT NULL, 
	[SubjectId] NVARCHAR(30) NOT NULL, 
	[Type] NVARCHAR(40) NOT NULL,
	[Enabled] BIT NOT NULL DEFAULT 1
)
